version: "3.9"

services:
  app:
    container_name: russian-rep-backend
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./data/osu-cache:/app/osu_cache
      - ./data/:/app/data
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: ${DB_CONN}
      IrcConnection__Nickname: ${IRC_NICK}
      IrcConnection__Server: ${IRC_SERVER}
      IrcConnection__Port: ${IRC_PORT}
      IrcConnection__Password: ${IRC_PASS}
      IrcConnection__Channel: ${IRC_CHANNEL}
      IrcConnection__UseSsl: ${IRC_USESSL}
      OsuApi__ClientId: ${OSU_ID}
      OsuApi__ClientSecret: ${OSU_SECRET}
      OsuApi__RedirectUri: ${OSU_REDIRECT}
      OsuApi__TokenFilePath: ${OSU_TOKEPATH}
      OsuApi__AllowedUserId: ${OSU_USER}
      OsuApi__ChannelId: ${OSU_CHANNEL}
      ChatMode: ${CHAT_MODE}
    networks: [osu-russian-rep]
    restart: unless-stopped

  db:
    image: postgres:14
    container_name: osu-rep-db
    environment:
      POSTGRES_DB: OsuReputation
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "10.8.1.1:5432:5432"
      - "127.0.0.1:5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks: [osu-russian-rep]
    restart: unless-stopped
volumes:
  pgdata:

networks:
  osu-russian-rep:
    name: osu-russian-rep
    driver: bridge
